language: node_js
node_js:
  - "8"
cache:
directories:
  - "node_modules"
before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install -g yarn
- yarn
- ng build

script: ng test --single-run