sudo: required
dist: trusty
language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

jobs:
  include:
    - stage: tests
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
        - npm install -g yarn
        - yarn
      script: ng test --single-run
    - state: tests
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
        - npm install -g yarn
        - yarn
      script: ng e2e --single-run
    - stage: Deployment
      script: skip
      before_deploy: npm run build:dynamic
      skip_cleanup: true
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: poller-spa
        on:
          branch: master
    - stage: Test Deployment
      script: 'curl https://poller-spa.herokuapp.com'